"""init database

Revision ID: 6cf225b5f311
Revises: f09e926ab619
Create Date: 2018-04-02 14:53:47.372109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf225b5f311'
down_revision = 'f09e926ab619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'created_at')
    # ### end Alembic commands ###
